networks:
  soroban-equillar:
    external: true

services:
  database:
    image: postgres
    container_name: equillar-db
    ports:
      - "5497:5432"
    environment:
      POSTGRES_DB: equillar
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
    networks:
      - soroban-equillar
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: equillar-app
    ports:
      - "8000:8000"
    depends_on:
      - database
    networks:
      - soroban-equillar