version: '3'

networks:
  soroban-crowdfactoring:
    external: true

services:
  database:
    image: postgres
    container_name: crowdfactoring-db
    ports:
      - "5497:5432"
    environment:
      POSTGRES_DB: sbcrowdf
      POSTGRES_PASSWORD: sbcrowdf
      POSTGRES_USER: sbcrowdf
    networks:
      - soroban-crowdfactoring